export type Quote = { text: string; author: string };

// Rotates once per calendar day so everyone sees the same quote that day —
// mixes original messages signed by Andrés Damián (CEO de Provedix) with
// well-known quotes from famous entrepreneurs/leaders, all in Spanish.
// Themes: trabajo en equipo, disciplina, autocontrol, honestidad, integridad,
// mentalidad empresarial — shown at the top of Inicio for admin and every
// employee.
const QUOTES: Quote[] = [
  { text: "El éxito de Provedix no lo hace una persona, lo hace un equipo que decide remar en la misma dirección todos los días.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
  { text: "La disciplina es la puente entre las metas y los logros. No esperes sentirte motivado — empieza, y la motivación llega sola.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Si quieres ir rápido, ve solo. Si quieres llegar lejos, ve acompañado.", author: "Proverbio africano" },
  { text: "La honestidad no es negociable. Prefiero un error contado a tiempo que una mentira bien disimulada.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La calidad nunca es un accidente; siempre es el resultado de un esfuerzo inteligente.", author: "John Ruskin" },
  { text: "El autocontrol es la fuerza silenciosa que separa a los buenos colaboradores de los excelentes.", author: "Andrés Damián, CEO de Provedix" },
  { text: "No tengas miedo de renunciar a lo bueno para ir por lo grandioso.", author: "John D. Rockefeller" },
  { text: "Cada tarea bien hecha, por pequeña que parezca, construye la reputación de toda la empresa.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
  { text: "No busco personas perfectas, busco personas comprometidas — la perfección se aprende, el compromiso se decide.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
  { text: "Un equipo fuerte no es el que nunca se equivoca, es el que se levanta rápido y sigue adelante juntos.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", author: "Michael Jordan" },
  { text: "La integridad se mide en los momentos en que nadie está mirando.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La disciplina es el puente entre las metas y los logros.", author: "Jim Rohn" },
  { text: "Trabajar con propósito transforma una tarea en un logro.", author: "Andrés Damián, CEO de Provedix" },
  { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
  { text: "La confianza se gana en años y se pierde en segundos — cuídala como el activo más valioso que tienes.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Un sueño no se convierte en realidad a través de la magia; se necesita sudor, determinación y trabajo duro.", author: "Colin Powell" },
  { text: "No hay atajos para la excelencia, solo constancia disfrazada de paciencia.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La honestidad es el primer capítulo del libro de la sabiduría.", author: "Thomas Jefferson" },
  { text: "Cuando ayudas a crecer a tu compañero, toda la empresa crece contigo.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El carácter es hacer lo correcto cuando nadie está mirando.", author: "J.C. Watts" },
  { text: "La puntualidad es la primera muestra de respeto hacia tu equipo y hacia tus clientes.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Nunca es demasiado tarde para ser quien podrías haber sido.", author: "George Eliot" },
  { text: "Provedix no crece por suerte, crece porque cada uno de ustedes decide dar un poco más cada día.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La grandeza no se mide por lo que se logra, sino por la oposición que se ha superado.", author: "Booker T. Washington" },
  { text: "El verdadero liderazgo no se impone, se gana con el ejemplo diario.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El liderazgo es la capacidad de traducir la visión en realidad.", author: "Warren Bennis" },
  { text: "Cada cliente satisfecho es el resultado de decisiones bien tomadas por todo un equipo.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.", author: "Vidal Sassoon" },
  { text: "La proactividad no espera instrucciones: ve el problema y ya está resolviéndolo.", author: "Andrés Damián, CEO de Provedix" },
  { text: "No esperes el momento perfecto, toma el momento y hazlo perfecto.", author: "Zig Ziglar" },
  { text: "No le tengas miedo al error, tenle miedo a no intentarlo.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La motivación te pone en marcha, el hábito te mantiene en marcha.", author: "Jim Rohn" },
  { text: "El compromiso real se nota en los días difíciles, no en los fáciles.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el valor de continuar.", author: "Winston Churchill" },
  { text: "Cuida los detalles — en e-commerce, un pequeño detalle puede ser la diferencia entre un cliente feliz y uno perdido.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Si no construyes tu sueño, alguien más te contratará para construir el de ellos.", author: "Tony Gaskins" },
  { text: "La mejor versión de Provedix nace de la mejor versión de cada uno de ustedes.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La forma de empezar es dejar de hablar y empezar a hacer.", author: "Walt Disney" },
  { text: "Ser honesto contigo mismo sobre tus errores es el primer paso para mejorar de verdad.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Todos nuestros sueños pueden hacerse realidad si tenemos el coraje de perseguirlos.", author: "Walt Disney" },
  { text: "La disciplina no te quita libertad, te la da — porque el orden de hoy es el tiempo libre de mañana.", author: "Andrés Damián, CEO de Provedix" },
  { text: "No mires el reloj; haz lo que él hace. Sigue moviéndote.", author: "Sam Levenson" },
  { text: "Un buen equipo se reconoce por cómo se trata cuando las cosas se complican.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El éxito en los negocios requiere entrenamiento, disciplina y trabajo duro.", author: "David Rockefeller" },
  { text: "No midas tu día por las horas trabajadas, mídelo por el valor que aportaste.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La confianza en uno mismo es el primer secreto del éxito.", author: "Ralph Waldo Emerson" },
  { text: "La confianza en uno mismo se construye cumpliendo las pequeñas promesas que te haces cada día.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Un líder es el que conoce el camino, va por el camino y muestra el camino.", author: "John C. Maxwell" },
  { text: "Cada área de esta empresa depende de las demás — nadie gana solo.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El respeto se gana, la honestidad se aprecia, la confianza se merece y la lealtad se retorna.", author: "Anónimo" },
  { text: "Gracias por elegir dar lo mejor de ustedes cada día. Eso es lo que hace grande a Provedix.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Trata a las personas como si fueran lo que deberían ser, y las ayudarás a convertirse en lo que son capaces de ser.", author: "Johann Wolfgang von Goethe" },
  { text: "La excelencia es un hábito, no un accidente.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Cuida a tus empleados y ellos cuidarán tu negocio.", author: "Richard Branson" },
  { text: "Estoy orgulloso de este equipo — sigan creciendo, que Provedix crece con cada uno de ustedes.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El cliente no siempre tiene la razón, pero siempre debe sentir que la tiene.", author: "Anónimo" },
  { text: "El éxito de un equipo no es la suma de lo que cada uno puede hacer solo, es lo que todos pueden hacer juntos.", author: "Vince Lombardi" },
  { text: "La calidad de un líder se refleja en los estándares que se pone a sí mismo.", author: "Ray Kroc" },
  { text: "No hay atajos hacia ningún lugar que valga la pena llegar.", author: "Beverly Sills" },
  { text: "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.", author: "Henry Ford" },
  { text: "Si crees que puedes, o si crees que no puedes, en ambos casos tienes razón.", author: "Henry Ford" },
  { text: "La perseverancia no es una carrera larga; son muchas carreras cortas, una tras otra.", author: "Walter Elliot" },
  { text: "El trabajo duro vence al talento cuando el talento no trabaja duro.", author: "Tim Notke" },
  { text: "Nunca dejes que el miedo a perder sea mayor que la emoción de ganar.", author: "Robert Kiyosaki" },
  { text: "La integridad es hacer lo correcto, incluso cuando nadie está mirando.", author: "C.S. Lewis" },
  { text: "Lo que haces habla tan fuerte que no puedo oír lo que dices.", author: "Ralph Waldo Emerson" },
  { text: "Ninguno de nosotros es tan inteligente como todos nosotros juntos.", author: "Ken Blanchard" },
  { text: "El progreso es imposible sin cambio, y quienes no pueden cambiar su mente no pueden cambiar nada.", author: "George Bernard Shaw" },
  { text: "No hay ascensor hacia el éxito, hay que tomar las escaleras.", author: "Zig Ziglar" },
  { text: "La puntualidad es el alma del negocio.", author: "Thomas Chandler Haliburton" },
  { text: "El éxito parece estar conectado con la acción. Las personas exitosas se mantienen en movimiento.", author: "Conrad Hilton" },
  { text: "Cuando trabajas en equipo, trabajas con las fuerzas de todos, no solo con las tuyas.", author: "Anónimo" },
  { text: "Contrata carácter. Entrena habilidad.", author: "Peter Schutz" },
  { text: "El respeto verdadero por uno mismo es lo que hace que una persona se discipline.", author: "Abraham Joshua Heschel" },
  { text: "La actitud es una pequeña cosa que marca una gran diferencia.", author: "Winston Churchill" },
  { text: "El logro de un equipo se mide por el resultado, no por las excusas del camino.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Un negocio hecho solo de números olvida que detrás de cada número hay una persona.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene.", author: "Zig Ziglar" },
  { text: "No hay viento favorable para el que no sabe a dónde va.", author: "Séneca" },
  { text: "La grandeza no es dónde estás parado, sino en qué dirección te mueves.", author: "Oliver Wendell Holmes" },
  { text: "El valor de una idea radica en el uso que se hace de ella.", author: "Thomas Edison" },
  { text: "Rodéate de personas que hablen bien de ti a tus espaldas.", author: "Warren Buffett" },
  { text: "Aquí no premiamos al que más habla, premiamos al que más resuelve.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El precio del éxito es el trabajo duro, la dedicación al trabajo en cuestión y la determinación.", author: "Vince Lombardi" },
  { text: "La vida es 10% lo que te pasa y 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
  { text: "Un equipo unido en el error crece más que un equipo dividido en el acierto.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El único modo de hacer un trabajo grandioso es amar lo que haces, y si no lo has encontrado, sigue buscando.", author: "Steve Jobs" },
  { text: "La grandeza de una empresa se mide por cómo trata a quienes menos pueden defenderse.", author: "Anónimo" },
  { text: "No dejes para mañana el compromiso que puedes demostrar hoy.", author: "Andrés Damián, CEO de Provedix" },
  { text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", author: "Séneca" },
  { text: "La responsabilidad es el precio de la grandeza.", author: "Winston Churchill" },
  { text: "Sean la razón por la que alguien más confía en que las cosas se van a hacer bien.", author: "Andrés Damián, CEO de Provedix" },
  { text: "Un buen líder inspira a la gente a tener confianza en el líder; un gran líder inspira a la gente a tener confianza en sí misma.", author: "Eleanor Roosevelt" },
  { text: "El trabajo en equipo es el combustible que permite que la gente común logre resultados poco comunes.", author: "Andrew Carnegie" },
  { text: "Las personas olvidan lo rápido que hiciste un trabajo, pero recuerdan lo bien que lo hiciste.", author: "Howard Newton" },
  { text: "Aquí valoramos más a quien pregunta y aprende que a quien calla y se equivoca por orgullo.", author: "Andrés Damián, CEO de Provedix" },
  { text: "El carácter no se puede desarrollar con facilidad y tranquilidad. Solo a través de una experiencia de prueba y sufrimiento el alma se fortalece.", author: "Helen Keller" },
  { text: "El compromiso convierte una promesa en realidad.", author: "Abraham Lincoln" },
  { text: "Sean puntuales, sean honestos, sean el ejemplo que quisieran ver en los demás.", author: "Andrés Damián, CEO de Provedix" },
];

function dayOfYear(date: Date) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / 86400000);
}

export function getDailyQuote(): Quote {
  return QUOTES[dayOfYear(new Date()) % QUOTES.length];
}
