-- AlterTable
ALTER TABLE "StockKardexJustComparison" ADD COLUMN     "avgCostDifference" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "investockAvgCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "justAvgCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
